language: node_js
sudo: false
node_js: stable
env:
  matrix:
  - CMD=build
  - CMD=test
matrix:
  fast_finish: true
  allow_failures:
  - env: CMD=build
script:
- npm run $CMD
notifications:
  email: false
