project_identifier_env: CROWDIN_KANTO_RIDRES_PROJECT_ID
api_key_env: CROWDIN_KANTO_RIDRES_API_KEY
base_path: ./
preserve_hierarchy: true
files:
  - source: /docs/*.md
    translation: /website/translated_docs/%locale%/%original_file_name%
    languages_mapping:
      locale:
        es-US: en
        ja-JP: ja
  - source: /website/i18n/en.json
    translation: /website/i18n/%locale%.json
    languages_mapping:
      locale:
        es-US: en
        ja-JP: ja
